### ISSUE TITLE
unused constructors

### ISSUE THREAD

**Issue by akwong189** [2643/2017-Code#1]
Unless declaring the class in Robot.java, you do not need constructors. The reason is that the methods are already static, meaning that any class within the same package can call them. If you want to use constructors, declare a variable for the class and call theVariable.theMethod()

**Comment by klinville** [comment]
I've pointed out that there is an excessive use of static variables in the code. Please try to limit what variables are available to outside classes by using constructor parameters more (not less). It's a key principal in OO programming called encapsulation.
  I'd be happy to go over this with the team. The one-by-one conversations don't seem to be working.

Cheers,
Kevin

On Feb 12, 2017, at 10:57 PM, Adley Wong <notifications@github.com<mailto:notifications@github.com>> wrote:


Unless declaring the class in Robot.java, you do not need constructors. The reason is that the methods are already static, meaning that any class within the same package can call them. If you want to use constructors, declare a variable for the class and call theVariable.theMethod()
